export const images = [
  { path: "assets/images/gallery/img1.jpg" },
  { path: "assets/images/gallery/img2.jpg" },
  { path: "assets/images/gallery/img3.jpg" },
  { path: "assets/images/gallery/img4.jpg" },
  { path: "assets/images/gallery/img5.jpg" },
  { path: "assets/images/gallery/img6.jpg" },
  { path: "assets/images/gallery/img7.jpg" },
  { path: "assets/images/gallery/img8.jpg" },
  { path: "assets/images/gallery/img9.jpg" },
  { path: "assets/images/gallery/img10.jpg" },
  { path: "assets/images/gallery/img11.jpg" },
  { path: "assets/images/gallery/img12.jpg" },
  { path: "assets/images/gallery/img13.jpg" },
  { path: "assets/images/gallery/img14.jpg" },
  { path: "assets/images/gallery/img15.jpg" },
  { path: "assets/images/gallery/img16.jpg" },
  { path: "assets/images/gallery/img17.jpg" },
  { path: "assets/images/gallery/img18.jpg" },
  { path: "assets/images/gallery/img19.jpg" },
  { path: "assets/images/gallery/img20.jpg" },
  { path: "assets/images/gallery/img21.jpg" },
  { path: "assets/images/gallery/img22.jpg" },
  { path: "assets/images/gallery/img23.jpg" },
];
